export const FETCH_ATTRACTIONS_START = 'FETCH_ATTRACTIONS_START';
export const FETCH_ATTRACTIONS_SUCCESS = 'FETCH_ATTRACTIONS_SUCCESS';
export const FETCH_ATTRACTIONS_FAIL = 'FETCH_ATTRACTIONS_FAIL';

