export const FETCH_ATTRACTIONS_START = 'FETCH_ATTRACTIONS_START';
export const FETCH_ATTRACTIONS_SUCCESS = 'FETCH_ATTRACTIONS_SUCCESS';
export const FETCH_ATTRACTIONS_FAIL = 'FETCH_ATTRACTIONS_FAIL';

export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SELECT_ALL_CATEGORIES = 'SELECT_ALL_CATEGORIES';
export const SELECT_DISTRICT = 'SELECT_DISTRICT';
export const SELECT_ALL_DISTRICTS = 'SELECT_ALL_DISTRICTS';